# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 620a2ae842120b4bec8d39567d156030ac31c07e7e1a3282e9fb2e90ded7c6ac849b6a6f222298f3eb61253e5020c0374e106004182a8a36f2adf0969b2dce2f
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: 70e129e2cc74742ca9c8dda1583ad922fa6eb2ee0a2dacaf8f756b4e3521ea76db55f0d0530277428abaa9ec4da01ea206f7e35ea629be48a40dd5907da758ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
